# MCP Desktop Notification Configuration Example
# Copy this file to the appropriate location for your platform:
#   Linux/macOS: ~/.config/mcp-desktop-notification/config.yaml
#   Windows: %APPDATA%\mcp-desktop-notification\config.yaml

notification:
  # Dry-run mode for testing (default: false)
  # When enabled, notifications are logged but not actually sent
  dry_run: false

  # Verbose logging for debugging (default: false)
  # Enable this only for testing and troubleshooting
  verbose: false

  # Message template configuration (NOT YET IMPLEMENTED - Coming in future release)
  # The current version uses message and title directly as provided
  # Future version will support: {{.Message}}, {{.Title}}, {{.Level}}, {{.Timestamp}}
  # template:
  #   default: "{{.Title}}: {{.Message}} [{{.Level}}]"

  # Notification level mappings
  # Configure urgency and icons for each severity level
  levels:
    info:
      urgency: "normal"
      icon: ""
    warning:
      urgency: "normal"
      icon: "dialog-warning"
    error:
      urgency: "critical"
      icon: "dialog-error"
    success:
      urgency: "low"
      icon: "dialog-information"
